site_name: Build NNEZ Wiki
site_url: https://example.com/
nav:
    # - Home: 'index.md'

    # - Home: index.md
    # - About: about.md
  - 简介:
    - 快速开始: index.md
    - 参与活动: intro/htc.md
    - 服务器规则: intro/rule.md
    - F.A.Q: intro/faq.md
  - 活动:
    - '2021暑假': events/2021-summer-holiday.md
    - '2021春节': events/2021-spring-festival.md
    - '2021元旦': events/2021-new-year.md
    - '2020暑假': events/2020-summer-holiday.md
  - 关于:
    - 建设:
      - 测绘: about/construct/mapping.md
      - 建筑: about/construct/building.md
      - 内饰: about/construct/decoration.md
    - 加入我们:
      - 建造者: about/joinus/builder.md
      - 技术员: about/joinus/technician.md
theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js